#!/bin/bash
#
# This completes the parts of the install that aren't 
# currently/easily terraformed
#

#
# Install LoadBalancer support for nginx-ingress
#
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
#kubectk apply -f ./metallb-native.yaml

# Wait for the install to complete...
echo
echo "Waiting for metallb to complete the install..."
echo

kubectl wait --namespace metallb-system \
                --for=condition=ready pod \
                --selector=app=metallb \
                --timeout=90s

kubectl apply -f ./metallb-conf.yaml

#
# Install flagger
#
helm upgrade -i flagger flagger/flagger \
--namespace ingress-nginx \
--set prometheus.install=true \
--set meshProvider=nginx

exit 0
