#
# This can be modularized in terraform
#
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: example
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/mpeters0n/flagger-poc
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: example
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./terraform/example
  sourceRef:
    kind: GitRepository
    name: example
    namespace: flux-system
