locals {
  app_name = "example"
  app_team = "devops"
  env      = "dev"
}

provider "kubernetes" {
#  config_path    = "/home/mpeterson/kind.kubeconfig"
#  config_context = "kind"
  host                   = "https://192.168.1.101:45351"
  cluster_ca_certificate = base64decode("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1ESXdOakl4TkRRek1sb1hEVE0wTURJd016SXhORFF6TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjY2CjIxWVhFUi81WGI3dElzd1VGMU1YQUp4UGZzR2lnTktIV1J4dmhPTkdaMWp6Kzd5UzJab21hTFFCeUxBZ3VnS20KaHZtZWQ5dHhLc3poemxYY2hUSlZUNEttSVdwME9nQmsvMm8rREdtU1pUSXFEL0pKcEtURFNSdWZEbjJVV3pPaApUVnRoSk44M1RhUCtISVlpSEM0eHBGOEVUUHQvVzJHanNrOG5YclYwVk1tRHdRUkZTZEJQdFIxaks1NWt3VHcrCkNoa0lUeVJGMTVyQ1dXMC9oUE4xVkRDZEhSMHRhbkFFa2ZyQXJLK0dYYjBjc2I4K3l4NURHV082bm9DSWE4ak0KaW5RNnZ3a3ZUZUVhdFgyUldLZEpCdjViWG42UmloQUZHNlREalNJanpNNWJReGwxOUUrcnpEYjlWVlJLVDUwcApDVmo1WmtDOTQvTkdmdDhaZkEwQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZHZ0JnTEEwNG5zQ1NKL3IxSkJJMmR3OHU3Ky9NQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRitCRVlNTG5rbGRDaGd2ZlpxTwpZMnhYZ1BwdlMzcnpMMTdqcGxFYlNyODZBb0pickY4eGhra0xNK3hpUm1TaXhmbHR3NmpxazVVVUNjTTJWNTdQCjZUOU84SS9mVU1wOWFpWHVacWtWSHllVFh6cjVleFd6U2RiQXRxQ20yQzNBNHVJRnpvNS9HWTZ3ZXB5RlV2M2gKakw5OWtUU2dPUEtpV1pBM1EwaFA4dE4remhLTG5UNGY2a1FpQWhYOHZpOWF0TXkwSGJUSVBXTHB2MzZ1L0dGUAo5MVBNeE44ZjBVRitaUzlBUU4wdWlZZk5wSW1jbWhBaTRaWHVBMXhkaGluM3Fic21EOFN1WFBsRkRGbnB5b1dNCjZxbzFJaTNEVVFsbGtJQXVjejk5V0dKMUtvUkgveW5rTDUzQllMNkpJdWtPNG5pRmc3UC8yZEMwUmVFMmRHeVQKWGZRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==")
  client_key             = base64decode("LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBNjZGbEpSNy9NS1RuWDY5WlNqblRxdHVzMWZtQmU1bmdRRi9hWUtPQUNhS0RzamJhCkdqVDU5SjR5cHFYS2Z6eHpiemxkcURRMHROYjFaQnZBa04ydk9VM29QYk83cE1KUWVjaWNuYVJ6bUtHa1grNU0KSmtGb05OU1Jsc1RpMkpxYnRNZGtsczV5MHR5N3QyNWlqMjZTMXplK3MrUE5WTEpTcXNYaVY1QnlCSXRDRTRTaQpTWXQvMytTLzBHM1Fnb0pJUWNvTFVqclgyY29YZlluQW0xWGFicE9ZMFVMMWg1OTlZSWUvM3VIeHFUeHppNTlmCjd6SU5xZVVlaDlVem5PZEVOOG1nRDFRbVVPWVVHYjVNb04xMXl4ZGVrc3Ara0xUNzFOK2c4Zm92Y2RuOVErbEcKcTVOVm9heVNFK0ZmNk9IWW9lTGdHTnlyN0x0ZnZqRldpclpWWXdJREFRQUJBb0lCQUVYZlpFanZ1aWpJbmJ2bwpHWWhEUVp0RzdTZStoMEVKemxBSW5JOVByS1l1eFBMU0JUY0VRcUxoVG8vUVZnNEk5UW9rYnJ0MFQ3VFlrWWdRCkdyaGFwSjFQbHZERkhYMnNDWVV6a2czRk9Hb29kTC9sd0RzUDVrRFVVQi92WG4xd3kzOStLVHYzR0dHakJ4OUwKNG5vNkJkMUFNSkxUbUkzbkcxQjh3YlBKcDZYa3ZBMUJKLzhDRStEVFdpQXdSUEZSdlRyOHIxcXg0RjhuS2tSRwpvaHdVNVNCMlBTM3dxTC9qZ3YvdlgyZUpJQTgrNWNxQjkwMmlrUENBTk9Sa1NqR3laM3Z1MWprR29IUE4ySW8yCnlzZkVLbDRoVkpWQ1JsY09IK3VFU3o5Zys0K2EyejdITGpVbE9rTTY1UGpYZE05Wi9EekVEUmJ2OWNybktSNmsKeEZaRmpTRUNnWUVBKzRGTlhXbTBsK1AzcFFqbGxQZW5rU0d5Wi9meHFRMHYwcjZuTCs3TXJ1ZUhTRVR2aXFwUQpwQ0ZHUFVsdzkzenRON3FtUE8vWiszUFhlN2M5dWViMGpuVFBSa2gyMjhqNWl4c2VERmwzTVZnRjF6V3Q4M2xXCnFkVXFsWGZiNlhFTFVqUFYrbWNaWDg1VFByVW9Dc3FyelAzMnR0NWt1eU90VndFV1BTUkFkUWtDZ1lFQTc5ZDIKWnlYV3RjaXE5dlNhcjVtZ0VCVzJtbE1HVGIzaHJEWk1OTEV2allQbEhmMFdTVjg5cjVvZDdRakdlVmFibjBkWQoya24wMkpzTUVER2JYZXFVSStHNEVDdElWeERXaURRWEI3dmpIZ2lpNU85NTZ0Y0d3dGQ1aFNVdFZLdCtxLzFkClNpZlI0aHp4ZC81czJ4bmFocjVLWnEzNjVST1pxbGhWNDc4NFhnc0NnWUJneWNrQkt2M2gra3hDaWVMNGFqcGwKWXVkcWxZTzl3Q0pvWXhDcUpLZEdwRGx1dVlES0IzTlRScTdtUlE0aFlFVldUaEZOb0N4dVZZMVd3aFVTSnV4MApxa1ZlVWVMVUFFcndtclg4b0sxN0l0blVrWWJwRFFncUFhd0txMzdKSHNUeGxKdERhMHZiaitaL1dtNFhnUm1PCm9TbkNCR0lWbHN4TmtGQ0RwU0RkS1FLQmdDdVBoNXErWFp2UW9YU1BBcFZJSXJFcE1Hd2hEakVLZnJWbmV6bksKd0tkRVFGWE5CTUk0d1J4bXNtNjl2RWFIZTJaWGNBVGRqOUhUZjBKbHNDRkRuTHBUb2JtV0V1SjFWWEdSZkdsVQpMN0Rod3F3djdvVy9uaU8vUFB2NHY1MzBNK0tLOXVta0I5TzRqQWJPTi9rblhmQkJHWVJDcnlIeUNHUE8vWEtLCjVYTDNBb0dBSHp4SGpOM1pLdjZDeURyejhrR2wyKzFwWWNlbFhDYzNvM1hoYlNBL3lqWlZKakVDQjdBRlNqNE0KRUc3OWRKMWFWbzNnVzE3V0lRRkkyR0krbWw1MWVPdm1POENHOU5HZjlWT2oxVTF3QVJUeE4zUDBFbjU0dThMcgpYMlZ5VW5vUVNlUStuUW5SZGU5aEZHc2UzQW5MTzhucXVXQVBNR3hpUWhOc3VNY0UwUEE9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==")
  client_certificate     = base64decode("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJQUxDbGpLL21veFF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeU1EWXlNVFEwTXpKYUZ3MHlOVEF5TURVeU1UUTBNelJhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTY2RmxKUjcvTUtUblg2OVoKU2puVHF0dXMxZm1CZTVuZ1FGL2FZS09BQ2FLRHNqYmFHalQ1OUo0eXBxWEtmenh6YnpsZHFEUTB0TmIxWkJ2QQprTjJ2T1Uzb1BiTzdwTUpRZWNpY25hUnptS0drWCs1TUprRm9OTlNSbHNUaTJKcWJ0TWRrbHM1eTB0eTd0MjVpCmoyNlMxemUrcytQTlZMSlNxc1hpVjVCeUJJdENFNFNpU1l0LzMrUy8wRzNRZ29KSVFjb0xVanJYMmNvWGZZbkEKbTFYYWJwT1kwVUwxaDU5OVlJZS8zdUh4cVR4emk1OWY3eklOcWVVZWg5VXpuT2RFTjhtZ0QxUW1VT1lVR2I1TQpvTjExeXhkZWtzcCtrTFQ3MU4rZzhmb3ZjZG45UStsR3E1TlZvYXlTRStGZjZPSFlvZUxnR055cjdMdGZ2akZXCmlyWlZZd0lEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JSb0FZQ3dOT0o3QWtpZjY5U1FTTm5jUEx1Lwp2ekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBTjIvdG9jZWNjeHdRY1c2aGtGQWVnd2lPMC9YQmw3NTF2eWM1ClNUczU3cHg1a3VmRml4d0ljK0UyWnZKaTgvWm50a2Q2cFJVSXkrL2NSdFJNaVhvbjQ1N3JsNkx5M2gvMnYvb2gKSitaa2JsbkEzZ2QxNHo2Y0ZJVmpKS2tOY2dZUWwwTjVyL3RDc0YvSW4rTHBZZVRRWWF0NFRnUXNkUlpaVG96Nwp3dnc4NjRHekRrS2ZhQk5McmR3TTVETUE0QVErRGE0MFdJQUpEcTRMYTI3ZDNIa1FQNWV1VkV2TFFpRFQ1aklOCjJhNnlUclpySjJzSzRnWDFyUU1JWU56VENsL0xraDlwUjhIRHFBZ2FIZ0RQdEM3ZFFyWlAxbXZPVTB3MndWK20KSmpqUU02U3pPRUlIcm56WHpZbERzbHA5aDNWQlVGM2ZZQ3FBY1hMYmdBQktZcVVXU1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==")
}

resource "kubernetes_namespace" "this" {
  metadata {
    name = "example"
  }
}

resource "kubernetes_deployment" "this" {
  metadata {
    name      = local.app_name
    namespace = kubernetes_namespace.this.metadata.0.name
#    namespace = "flux-system"
  }

  spec {
    replicas = 1

    selector {
      match_labels = {
        "app.kubernetes.io/name" = local.app_name
      }
    }

    template {
      metadata {
        labels = {
          "app.kubernetes.io/name" = local.app_name
        }
      }
      spec {
        container {
          image = "nginx:1.21.6"
          name  = "example"

          resources {
            limits = {
              cpu    = "0.5"
              memory = "512Mi"
            }
            requests = {
              cpu    = "250m"
              memory = "50Mi"
            }
          }

          liveness_probe {
            http_get {
              path = "/"
              port = 80

              http_header {
                name  = "X-Custom-Header"
                value = "Awesome"
              }
            }

            initial_delay_seconds = 3
            period_seconds        = 3
          }
        }
      }
    }
  }
}
